# Generated by Django 3.2.16 on 2023-05-22 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0015_edit_solarschedule_events_choices'),
        ('periodic_instructor_reports', '0003_auto_20210723_0330'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodicreportschedule',
            name='crontab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.crontabschedule'),
        ),
        migrations.AlterField(
            model_name='periodicreportschedule',
            name='interval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.intervalschedule'),
        ),
    ]
